apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/christianh814/simple-go/deploy/overlays/default

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: simple-go
  patch: |
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 10

